spring:

  # DB 설정
  output.ansi.enabled: always
  datasource:
    url: 'jdbc:mysql://mysql:3306/diary'
    username: 'root'
    password: '1234'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'

  jpa:
    database: mysql
    generate-ddl: true
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 30
    open-in-view: false

  # 시큐리티 설정
  security:
    user:
      name: 'a'
      password: '1'
# 로그 설정
logging.level:
  org.hibernate.SQL: debug

# 포트 설정
server:
  port: 8085